spring:
#  mvc:
#    apiversion:
#      use:
#        path-segment: 1
#        supported: 1.0, 2.0
#        default: 1.0
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    generate-ddl: false
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.

  # SQL Initialization
  sql:
    init:
      mode: always
      data-locations: classpath:default-data/data.sql
      continue-on-error: false